name: .NET

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
      
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Publish
      run: dotnet publish -c release -r ubuntu.20.04-x64 -o ${GITHUB_REF/refs\/tags\//} --self-contained false
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ${GITHUB_REF/refs\/tags\//}
        path: ${GITHUB_REF/refs\/tags\//}
